project:
  name: "SoarAI"
  version: "1.0.0"
  description: "Paper artifact config (CNum GB models are primary; python models are just for reproducing model search results)"

run:
  run_id: "test_results"
  deterministic: true # For deterministic train-test data split and training (single-threaded data-prep and less compiler optimized)
  cnum_model_train_seed: 25
  data_prep_seed: 900
  py_model_train_seed: 42

paths:
  core:
    in_peak_list_dir: "../data/test_data/" # Directory where the input peak lists reside
    in_peak_list_filename: "test_peak_list.txt" # Path to input peak list
  
    run_root: "./" # Root directory of all output for the unique run
    
    data_dir: "data/" # Directory where processed data will be output
    data_out_peak_list_dir: "peak_lists/" # Directory where the reagent-ion-specific peak lists will be output
    data_combo_files_dir: "combo_files/" # Directory to which combo files are output (fully processed data)
    data_combo_unidentified_dir: "unidentified_compounds/" # Directory to which improperly labeled compounds are output
    
    model_output_dir: "models/" # Directory to which trained models are output
    pred_output_dir: "preds/" # Directory to output model predictions to for analysis

    pred_logit_output_dir: "logits/" # Directory to which raw prediction values are output

    data_combo_NO_train: "NO_train.csv" # Path to NO train combo file
    data_combo_NH4_train: "NH4_train.csv" # Path to NH4 train combo file
    data_combo_NO_test: "NO_test.csv" # Path to NO test combo file
    data_combo_NH4_test: "NH4_test.csv" # Path to NH4 test combo file

    venv:
      analysis_dir: ../analysis/ # analysis venv directory (for analyzing model predictions)
      py_models_dir: ../py_models/ # py_models venv directory (for training python models)

core:
  model_hyperparams:
    xgboost:
      NH4_reagent:
        n_learners: 100
        learning_rate: 0.1
        subsample: 1.0
      NO_reagent:
        n_learners: 100
        learning_rate: 0.1
        subsample: 1.0

    nn:
      NH4_reagent:
        epochs: 20
      NO_reagent:
        epochs: 20
